<a href='http://www.geneva-indoors.com/' class='international__competition-logo'><img src='pictures/logo-TGI-NationsCup.png' alt='logo Nations Cup by Tchoukball Geneva Indoors' /></a>
<div><?php echo getSimplePageContent(44); ?></div>
<h2>Résultats suisses</h2>
<h3 class="alt">Hommes</h3>
<table class="classementTourFinal">
    <tr>
        <th>Position</th>
        <th>Édition</th>
    </tr>
    <tr>
        <td></td>
        <td>2019</td>
    </tr>
    <tr>
        <td>4èmes</td>
        <td>2018</td>
    </tr>
    <tr>
        <td>4èmes</td>
        <td>2017</td>
    </tr>
    <tr>
        <td>2èmes</td>
        <td>2016</td>
    </tr>
    <tr>
        <td>5èmes</td>
        <td>2015</td>
    </tr>
    <tr>
        <td>3èmes</td>
        <td>2014</td>
    </tr>
    <tr>
        <td>2èmes</td>
        <td>2013</td>
    </tr>
    <tr>
        <td>1ers</td>
        <td>2012</td>
    </tr>
    <tr>
        <td>1ers</td>
        <td>2011</td>
    </tr>
    <tr>
        <td>1ers</td>
        <td>2010</td>
    </tr>
</table>
<h3 class="alt">Femmes</h3>
<table class="classementTourFinal">
    <tr>
        <th>Position</th>
        <th>Édition</th>
    </tr>
    <tr>
        <td></td>
        <td>2019</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2018</td>
    </tr>
    <tr>
        <td>2èmes</td>
        <td>2017</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2016</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2015</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2014</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2013</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2012</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2011</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2010</td>
    </tr>
</table>
<h3 class="alt">M18 Hommes</h3>
<table class="classementTourFinal">
    <tr>
        <th>Position</th>
        <th>Édition</th>
    </tr>
    <tr>
        <td></td>
        <td>2019</td>
    </tr>
    <tr>
        <td>2èmes</td>
        <td>2018</td>
    </tr>
    <tr>
        <td>2èmes</td>
        <td>2017</td>
    </tr>
    <tr>
        <td>1ers</td>
        <td>2016</td>
    </tr>
    <tr>
        <td>2èmes</td>
        <td>2015</td>
    </tr>
    <tr>
        <td>1ers</td>
        <td>2014</td>
    </tr>
    <tr>
        <td>1ers</td>
        <td>2012</td>
    </tr>
    <tr>
        <td>1ers</td>
        <td>2011</td>
    </tr>
    <tr>
        <td>1ers</td>
        <td>2010</td>
    </tr>
</table>
<h3 class="alt">M18 Femmes</h3>
<table class="classementTourFinal">
    <tr>
        <th>Position</th>
        <th>Édition</th>
    </tr>
    <tr>
        <td></td>
        <td>2019</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2014</td>
    </tr>
    <tr>
        <td>1ères</td>
        <td>2010</td>
    </tr>
</table>