<?php

if ($_SESSION["debug_tracage"]) {
    echo __FILE__."<BR>";
}

define("VAR_LOOK_BG_BODY", "FFFFFF");
define("VAR_LOOK_FONDS_INTERIEUR", "FFFFFF");
define("VAR_LOOK_FONDS_INTERIEUR_UNE_SUR_DEUX", "EEEEEE");
define("VAR_LOOK_FONDS_BARRE_TITRE_EQUIPE_SUISSE", "B8F5FA");
define("VAR_LOOK_COULEUR_SEPARATION", "#CC3333");
define("VAR_LOOK_COULEUR_ERREUR_SAISIE", "F191C7");
define("VAR_LOOK_COULEUR_SAISIE_VALIDE", "7CCD7C");
